---
version: '2'
services:       
    postgres:
        container_name: postgres
        image: postgres 
        ports:
            - "5432:5432"  
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "/var/lib/postgresql/data:/var/lib/postgresql/data"

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080
        restart: always
          

        